# SPDX-FileCopyrightText: Copyright (C) 2026 Adaline Simonian
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is part of Ordbok API.
#
# Ordbok API is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# Ordbok API is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Ordbok API. If not, see <https://www.gnu.org/licenses/>.

version: '3.8'
services:
  db:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=ordbokapi
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ordbokapi
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./.postgres:/var/lib/postgresql/data

  meilisearch:
    image: getmeili/meilisearch:v1
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_ENV=development
    ports:
      - '${MEILI_PORT}:7700'
    volumes:
      - ./.meili:/meili_data

  valkey:
    image: valkey/valkey:9
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ./.redis:/data
